### ISSUE TITLE
Liquid address validation

### ISSUE THREAD

**Issue by pirinskodxb** [BoltzExchange/boltz-python#28]
Traceback (most recent call last):
  File "/tmp/test.py", line 36, in <module>
    validate_address('GpijgBhNkKDR1wtwqd3x3gPo8XcEWJcSr4', 'liquidv1', 'L-BTC/BTC')
  File "/tmp/test.py", line 29, in validate_address
    print(addr.address(net))
  File "/usr/local/lib/python3.9/dist-packages/embit/script.py", line 25, in address
    raise ValueError("This type of script doesn't have address representation")
ValueError: This type of script doesn't have address representation

Testing BoltzClient's validate_address with a test script. I get the same error when attempting a reverse swap.

Seems embit/script.py:from_address() defaults to BTC. Maybe I missed something in my setup or config?

temp fix for me is modifying embit/script.py:
#from .networks import NETWORKS
from embit.liquid.networks import NETWORK

**Comment by kilrau** [comment]
That's an issue with liquid legacy addresses, see https://github.com/lnbits/boltz/issues/25 which is an issue of boltz-python.
